#!/usr/bin/env bash

set -e

WP_TARGET_SOURCE="https://i.imgur.com/7UmuWkS.jpg"
WP_DIR="$HOME/.config/.fade-wallpaper"
WP_STATE="$WP_DIR/state"
WP_TARGET="$WP_DIR/target"
WP_TARGET_RESIZED="${WP_TARGET}.resized"
WP_TARGET_BLENDED="${WP_TARGET}.blended"

mkdir -p "$WP_DIR"

[[ -f "$WP_TARGET" ]] || wget -O "$WP_TARGET" "$WP_TARGET_SOURCE"

original_wallpaper() {
    local WP_BACKUP="$WP_DIR/original"
    local WP_CURRENT
    WP_CURRENT="$(gsettings get org.gnome.desktop.background picture-uri \
                  | sed -e "s|^'file://\\(.*\\)'$|\\1|")"

    if [[ "$WP_CURRENT" != "$WP_TARGET_BLENDED" ]]; then
        rm -f "$WP_STATE" &>/dev/null

        if ! diff "$WP_BACKUP" "$WP_CURRENT" &>/dev/null; then
            cp "$WP_CURRENT" "$WP_BACKUP"
        fi
    fi

    echo "$WP_BACKUP"
}

advance_state() {
    local CURR

    CURR="$(cat "$WP_STATE" 2>/dev/null)"
    [[ "$CURR" ]] || CURR=1
    CURR="$((CURR * 2))"
    if [[ "$CURR" -ge 100 ]]; then
        CURR=100
    fi

    echo "$CURR" | tee "$WP_STATE"
}

generate_wallpaper() {
    local WP_ORIGINAL
    WP_ORIGINAL="$(original_wallpaper)"
    local WP_SIZE
    WP_SIZE=$(identify -format "%[fx:w]x%[fx:h]" "$WP_ORIGINAL")

    convert "$WP_TARGET" -resize "$WP_SIZE" "$WP_TARGET_RESIZED"
    composite -gravity center \
              -dissolve "$(advance_state)" "$WP_TARGET_RESIZED" "$WP_ORIGINAL" \
              "$WP_TARGET_BLENDED"

    echo "$WP_TARGET_BLENDED"
}

gsettings set org.gnome.desktop.background picture-uri "'file://$(generate_wallpaper)'"
